Shared component
Team-MansuMugang/mansumugang-frontend pull request #22
Opened 2024-08-02 08:01 UTC by Hossdd

계정 컴퍼넌트들, 음성메세지 컴포넌트 추가 구현

2024-08-02 09:14 UTC, DUKY8N requested changes
전반적으로 잘 코딩했는데, 몇몇 부분에서 보안할 부분이 있는것 같습니당~

2024-08-02 09:14 UTC, DUKY8N commented on src/components/ContainerVoiceMessage.jsx
> +    <div className="ContainerVoiceMessage-container">
현재 class명에 카멜케이스와 케밥 표기법이 혼용되어 사용되고 있는 것을 확인했습니다.
HTML/CSS에서는 소문자와 하이픈 사용의 관례를 따르기 때문에 케밥 표기법 사용이 일반적입니다.
예를 들어, `ContainerVoiceMessage-container`라는 클래스명은 `container-voice-message-container`로 작성됩니다.
프로젝트에서도 케밥 표기법을 일관되게 사용하고 있으니, 이를 참고하여 클래스명을 수정해 주시면 감사하겠습니다.

그리고, `container-voice-message-container`와 같은 클래스명에서 'container'라는 단어의 중복 사용을 줄이는 것도 고려해주세요~!!

2024-08-02 09:14 UTC, DUKY8N commented on src/components/MoreContainer.css
> +.header {
현재 컴포넌트의 CSS에서 `header`와 `description`과 같은 범용적인 클래스명을 컴포넌트 클래스명으로 사용중인 것을 확인했습니다. 이러한 범용적인 클래스명은 다른 컴포넌트와의 스타일 충돌을 일으킬 수 있으므로, 아래와 같은 솔루션을 추천드립니다.

## CSS 복합 선택자 사용
CSS 복합 선택자들 중에서도 **CSS 후손(하위) 선택자**를 사용해서 같은 이름의 다른 클래스와의 충돌을 방지하는 방법입니다.
```css
.more-container .header { ... }
.more-container .description { ... }
```

## 컴포넌트 기반 네이밍
각 클래스명에 컴포넌트의 이름을 접두어로 사용해 고유한 클래스명을 제공하는 방식입니다. 
```css
.more-container-header { ... }
.more-container-description { ... }
```

위 두가지중 하나를 택하거나 혼용해서 사용하시는 것을 권장드립니다.

앞으로 점점 더 커질 프로젝트 규모를 생각해주시면서 클래스명 작성 부탁드립니다~~

2024-08-02 09:14 UTC, DUKY8N commented on src/components/ContainerWrapper.css
> +.description {
현재 컴포넌트의 CSS에서  `description`과 같은 범용적인 클래스명을 컴포넌트 클래스명으로 사용중인 것을 확인했습니다. 이러한 범용적인 클래스명은 다른 컴포넌트와의 스타일 충돌을 일으킬 수 있으므로, 아래와 같은 솔루션을 추천드립니다.

## CSS 복합 선택자 사용
CSS 복합 선택자들 중에서도 **CSS 후손(하위) 선택자**를 사용해서 같은 이름의 다른 클래스와의 충돌을 방지하는 방법입니다.
```css
.more-container .description { ... }
```

## 컴포넌트 기반 네이밍
각 클래스명에 컴포넌트의 이름을 접두어로 사용해 고유한 클래스명을 제공하는 방식입니다. 
```css
.more-container-description { ... }
```

위 두가지중 하나를 택하거나 혼용해서 사용하시는 것을 권장드립니다.

앞으로 점점 더 커질 프로젝트 규모를 생각해주시면서 클래스명 작성 부탁드립니다~~

2024-08-02 09:14 UTC, DUKY8N commented on src/pages/test/TestPage.jsx
> +          'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoGBxAQEBYQEBAWFhYWFhYWFhYWFhYWFhoWFhYZGRYZGBYaHysiGhwoHRkWIzQjKCwuMTExGSE3PDcwOyswMS4BCwsLDw4PGRERGTAoHygwMDAwMDAwMDAwMDAwMDAwMDAwM
Inline Base64를 하드코딩하는건 코드 가독성에 _매우매우매우매우매우매우_ 좋지 않습니다.
뿐만 아니라, Base64 인코딩은 원본 이미지 크기보다 약 33% 더 크기 때문에 로딩 시간과 대역폭 사용에 부정적인 영향을 줍니다.

이미지를 URL을 통해 불러오는 방식을 추천합니다.
현재 서버에 별도의 이미지 데이터가 없기 때문에, 다양한 테스트 이미지를 제공하는 서비스인 https://picsum.photos/ 의 이미지를 활용하는것을 추천드립니다.

2024-08-02 17:03 UTC, minnnisu commented
더운데 코딩하시느라 다들 고생이 많으시네요🥵
시원한 냉커피 한잔하면서 하세용ㅎㅎ

2024-08-03 09:29 UTC, DUKY8N approved these changes
굿굿! 고생했어~~

2024-08-03 09:29 UTC, merged